name: Linux CI

on: [push, pull_request]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0

    - name: qmake
      run: python config.py -q
      working-directory: .

    - name: make
      run: python config.py -b release
      working-directory: .
