name: MacOS CI

on: [push, pull_request]

jobs:      
  macOS:
    runs-on: macos-latest
    steps:

    - uses: actions/checkout@v2
    - name: Install Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: '3.7'
        architecture: 'x64'
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.3.0
             
    - name: qmake
      run: qmake -r CONFIG+=debug_and_release
      working-directory: ./src
      
    - name: make
      run: make
      working-directory: ./src
